// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIService exposes the streaming AI commands. Wails streams over named
 * events: each call carries a streamID and tokens are
 * emitted on the event "ai:<streamID>" (the frontend subscribes before calling
 * and unsubscribes on the terminal {type:"done"} / {type:"error"}). The first
 * parameter is context.Context so the frontend can cancel a stream (it is not
 * part of the generated TS signature).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "../internal/ai/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/models/models.js";

/**
 * Ask answers a question using the library as RAG context (FTS5 keyword
 * retrieval over chapter text), streaming the answer. Passing a bookID scopes
 * retrieval to that book — "ask this book" rather than "ask my library". Each
 * chapter contributes a bounded excerpt (its cached AI summary when it has one)
 * rather than its full text, so many chapters fit in one context window.
 * `history` is the prior conversation so a follow-up keeps its thread.
 */
export function Ask(question: string, bookID: number | null, history: ai$0.Message[] | null, streamID: string): $CancellablePromise<void> {
    return $Call.ByID(1902440655, question, bookID, history, streamID);
}

/**
 * Chat streams a plain assistant reply with no library context (pure chat),
 * keeping the recent conversation for follow-ups.
 */
export function Chat(question: string, history: ai$0.Message[] | null, streamID: string): $CancellablePromise<void> {
    return $Call.ByID(3016547228, question, history, streamID);
}

/**
 * Configured reports whether an LLM provider is usable right now. The UI needs
 * this to warn before a request is made ("this engine needs a key"), and asking
 * the backend is the only way to keep that warning honest: a provider can be
 * stored as a profile in the ai_providers list or in the older flat settings,
 * and only internal/ai knows the whole resolution. Reading one setting from the
 * frontend guessed at it, and guessed wrong for every profile-based config.
 */
export function Configured(): $CancellablePromise<boolean> {
    return $Call.ByID(3077645610);
}

/**
 * GetTranslation returns a cached chapter translation, or null when this
 * chapter has not been translated into this language by this engine.
 */
export function GetTranslation(bookID: number, chapterIndex: number, lang: string, engine: string): $CancellablePromise<models$0.ChapterTranslation | null> {
    return $Call.ByID(3592509009, bookID, chapterIndex, lang, engine);
}

/**
 * Summarize streams an AI summary of one chapter; a completed summary is
 * cached on the chapter so the next open is instant.
 */
export function Summarize(bookID: number, chapterIndex: number, streamID: string): $CancellablePromise<void> {
    return $Call.ByID(2500073931, bookID, chapterIndex, streamID);
}

/**
 * Translate translates one chapter into lang using engine ("llm" / "google" /
 * "deepl" / "bing"), streaming progress per batch over the event
 * "translate:<streamID>". The reassembled, sanitized result is cached and
 * reused on the next open — a chapter is long, and translation is billed by the
 * token. Each batch is re-sanitized here since engine output is untrusted.
 */
export function Translate(bookID: number, chapterIndex: number, lang: string, engine: string, streamID: string): $CancellablePromise<void> {
    return $Call.ByID(299801056, bookID, chapterIndex, lang, engine, streamID);
}
