// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CollectionService exposes shelf CRUD and ordering. A shelf groups books in
 * the sidebar; deleting one never deletes the books on it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/models/models.js";

/**
 * CreateCollection creates a shelf (idempotent on name) and returns its id.
 */
export function CreateCollection(name: string): $CancellablePromise<number> {
    return $Call.ByID(3856432364, name);
}

/**
 * DeleteCollection removes a shelf; its books stay in the library, unshelved.
 */
export function DeleteCollection(id: number): $CancellablePromise<void> {
    return $Call.ByID(4131188335, id);
}

/**
 * ListCollections returns every shelf with a live book count, ordered for the
 * sidebar.
 */
export function ListCollections(): $CancellablePromise<models$0.Collection[] | null> {
    return $Call.ByID(3536584185);
}

/**
 * RenameCollection renames a shelf, rejecting a clash with a different shelf.
 */
export function RenameCollection(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2159919262, id, name);
}

/**
 * ReorderCollections persists a new shelf ordering — ids in display order.
 */
export function ReorderCollections(ids: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(1327164908, ids);
}
