// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FontService exposes the font catalog and the download/install/remove commands
 * for the font-switching feature. Downloaded files land in <dataDir>/fonts and
 * are served to the webview by fonts.AssetMiddleware at /userfonts/<file>.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../internal/db/models.js";

/**
 * AddCustomFont downloads an arbitrary open-source font by URL (e.g. a GitHub
 * release asset), letting users add fonts beyond the curated catalog. The id is
 * derived from the URL so re-adding the same URL updates in place.
 */
export function AddCustomFont(url: string, family: string, axis: string, streamID: string): $CancellablePromise<void> {
    return $Call.ByID(501727730, url, family, axis, streamID);
}

/**
 * DeleteFont removes a downloaded font's record and file.
 */
export function DeleteFont(id: string): $CancellablePromise<void> {
    return $Call.ByID(816918095, id);
}

/**
 * ListInstalled returns the fonts the user has downloaded into the app data dir.
 */
export function ListInstalled(): $CancellablePromise<db$0.InstalledFont[] | null> {
    return $Call.ByID(1958321617);
}
