// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HighlightService exposes the highlight / annotation layer.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/models/models.js";

/**
 * CreateHighlight inserts a highlight and returns its new id. The anchor fields
 * (prefix / suffix / textOffset) let the frontend re-locate the span even after
 * the rendered text shifts.
 */
export function CreateHighlight(bookID: number, chapterIndex: number, quote: string, prefix: string, suffix: string, textOffset: number, color: string, note: string): $CancellablePromise<number> {
    return $Call.ByID(2608805550, bookID, chapterIndex, quote, prefix, suffix, textOffset, color, note);
}

/**
 * DeleteHighlight removes a highlight.
 */
export function DeleteHighlight(id: number): $CancellablePromise<void> {
    return $Call.ByID(312940987, id);
}

/**
 * DeleteHighlights removes a batch of highlights (the browser's multi-select
 * delete) in one transactional call rather than one IPC round-trip per row.
 */
export function DeleteHighlights(ids: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(621647320, ids);
}

/**
 * ExportSelectionMarkdown renders the given highlights — in the given order —
 * as one Markdown document. The Highlights browser passes the ids it is
 * showing (or just the ticked ones), so the file matches the screen rather
 * than re-deriving a filter the backend cannot see: a search term, a colour
 * filter and a date range compose there, and only the frontend knows the
 * result. Returns the saved path, or an empty string when the user cancels.
 */
export function ExportSelectionMarkdown(ids: number[] | null): $CancellablePromise<string> {
    return $Call.ByID(2965863463, ids);
}

/**
 * ListAllHighlights returns every highlight enriched with its book and chapter,
 * newest first — used by the Highlights browser panel.
 */
export function ListAllHighlights(): $CancellablePromise<models$0.HighlightWithContext[] | null> {
    return $Call.ByID(1210809088);
}

/**
 * ListBookHighlights returns every highlight in one book, in reading order —
 * what the reader's annotation panel shows.
 */
export function ListBookHighlights(bookID: number): $CancellablePromise<models$0.HighlightWithContext[] | null> {
    return $Call.ByID(808680914, bookID);
}

/**
 * ListHighlights returns the highlights inside one chapter, in reading order.
 */
export function ListHighlights(bookID: number, chapterIndex: number): $CancellablePromise<models$0.Highlight[] | null> {
    return $Call.ByID(3774060311, bookID, chapterIndex);
}

/**
 * SearchHighlights filters the global highlight list by quote, note, or
 * owning-book title. An empty query is equivalent to ListAllHighlights.
 */
export function SearchHighlights(query: string): $CancellablePromise<models$0.HighlightWithContext[] | null> {
    return $Call.ByID(3684953531, query);
}

/**
 * SetHighlightColor changes a highlight's colour (a palette key).
 */
export function SetHighlightColor(id: number, color: string): $CancellablePromise<void> {
    return $Call.ByID(1342658117, id, color);
}

/**
 * UpdateHighlightNote replaces a highlight's note (empty string clears it).
 */
export function UpdateHighlightNote(id: number, note: string): $CancellablePromise<void> {
    return $Call.ByID(2913439477, id, note);
}
