// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService is the frontend's entry point to the library: importing books,
 * listing them, reading them, and remembering where reading stopped.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../internal/db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/models/models.js";

/**
 * AddBookmark saves the current position under an optional label.
 */
export function AddBookmark(bookID: number, chapterIndex: number, ratio: number, page: number | null, label: string): $CancellablePromise<number> {
    return $Call.ByID(2276280588, bookID, chapterIndex, ratio, page, label);
}

/**
 * Counts are the numbers beside the sidebar's smart shelves.
 */
export function Counts(): $CancellablePromise<db$0.LibraryCounts> {
    return $Call.ByID(2948486885);
}

/**
 * CoverBytes returns a book's cover image.
 */
export function CoverBytes(bookID: number): $CancellablePromise<string | null> {
    return $Call.ByID(3756598731, bookID);
}

/**
 * DeleteBook removes a book and everything attached to it.
 */
export function DeleteBook(bookID: number): $CancellablePromise<void> {
    return $Call.ByID(1542825183, bookID);
}

/**
 * DeleteBookmark removes a bookmark.
 */
export function DeleteBookmark(id: number): $CancellablePromise<void> {
    return $Call.ByID(2904352426, id);
}

/**
 * GetBook loads a book's metadata, table of contents and saved position.
 */
export function GetBook(id: number): $CancellablePromise<models$0.BookDetail | null> {
    return $Call.ByID(3067814306, id);
}

/**
 * GetChapter returns one chapter's rendered body.
 */
export function GetChapter(bookID: number, index: number): $CancellablePromise<models$0.ChapterContent | null> {
    return $Call.ByID(1210081968, bookID, index);
}

/**
 * HasIndexedText reports whether a book's text has already been indexed, so a
 * PDF is read for it once rather than on every open.
 */
export function HasIndexedText(bookID: number): $CancellablePromise<boolean> {
    return $Call.ByID(2403243303, bookID);
}

/**
 * ImportBytes imports a book the frontend already holds — a file dropped onto
 * the window, which the webview hands over as bytes rather than as a path.
 */
export function ImportBytes(fileName: string, data: string | null): $CancellablePromise<models$0.ImportResult> {
    return $Call.ByID(3357137495, fileName, data);
}

/**
 * ImportFiles imports book files by path — what the file picker, a command-line
 * argument and a drop onto the dock all end up calling.
 */
export function ImportFiles(paths: string[] | null): $CancellablePromise<models$0.ImportResult[] | null> {
    return $Call.ByID(2327317251, paths);
}

/**
 * IndexPdfText stores the text behind a PDF's pages so the library can find
 * it. The frontend reads it with pdf.js — the Go side cannot, since a PDF's
 * pages are drawing instructions — and hands it over once per book.
 */
export function IndexPdfText(bookID: number, pages: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1872097868, bookID, pages);
}

/**
 * ListBookmarks returns a book's bookmarks in reading order.
 */
export function ListBookmarks(bookID: number): $CancellablePromise<models$0.Bookmark[] | null> {
    return $Call.ByID(3829997466, bookID);
}

/**
 * ListBooks returns the library grid for a sidebar selection.
 */
export function ListBooks(query: models$0.LibraryQuery, sortBy: string, limit: number, offset: number): $CancellablePromise<models$0.Book[] | null> {
    return $Call.ByID(2203990405, query, sortBy, limit, offset);
}

/**
 * PickAndImport opens the native file picker and imports whatever is chosen.
 * Returns one result per file: a batch where one file is corrupt still imports
 * the rest, and the frontend reports the failures individually.
 */
export function PickAndImport(): $CancellablePromise<models$0.ImportResult[] | null> {
    return $Call.ByID(792828904);
}

/**
 * ResourceBytes returns an image a chapter references through data-res. Wails
 * marshals a []byte as base64, which the frontend turns into a blob URL.
 */
export function ResourceBytes(bookID: number, path: string): $CancellablePromise<string | null> {
    return $Call.ByID(949784884, bookID, path);
}

/**
 * SaveProgress records where reading stopped. Called on a debounce as the
 * reader scrolls, so it stays a single cheap upsert.
 */
export function SaveProgress(bookID: number, chapterIndex: number, ratio: number, page: number): $CancellablePromise<void> {
    return $Call.ByID(396541147, bookID, chapterIndex, ratio, page);
}

/**
 * Search runs full-text search over chapter bodies, either across the library
 * or within one book.
 */
export function Search(text: string, bookID: number | null, limit: number): $CancellablePromise<models$0.SearchHit[] | null> {
    return $Call.ByID(1949681417, text, bookID, limit);
}

/**
 * SetCollection moves a book onto a shelf, or off every shelf when
 * collectionID is null.
 */
export function SetCollection(bookID: number, collectionID: number | null): $CancellablePromise<void> {
    return $Call.ByID(1808371163, bookID, collectionID);
}

/**
 * SetFlag toggles "finished" or "favorite" on a book.
 */
export function SetFlag(bookID: number, flag: string, on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1332988973, bookID, flag, on);
}

/**
 * SetPDFMetadata backfills what only a PDF renderer can know: the page count
 * and a cover rendered from page one. The frontend calls it the first time it
 * opens a PDF.
 */
export function SetPDFMetadata(bookID: number, pageCount: number, title: string, author: string, cover: string | null, coverMime: string): $CancellablePromise<void> {
    return $Call.ByID(1193077118, bookID, pageCount, title, author, cover, coverMime);
}

/**
 * SourceBytes returns the original file, which the PDF reader renders from.
 */
export function SourceBytes(bookID: number): $CancellablePromise<string | null> {
    return $Call.ByID(4076666243, bookID);
}

/**
 * UpdateMeta corrects a book's title and author.
 */
export function UpdateMeta(bookID: number, title: string, author: string): $CancellablePromise<void> {
    return $Call.ByID(4255848721, bookID, title, author);
}
