// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfo identifies this build — the About pane's version line and the
 * "copy diagnostics" affordance (version + platform for bug reports).
 */
export interface AppInfo {
    "version": string;
    "os": string;
    "arch": string;
}

/**
 * UpdateInfo is the result of an update check.
 */
export interface UpdateInfo {
    "current": string;
    "latest": string;
    "releaseUrl": string;
    "hasUpdate": boolean;
}
