// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingService exposes the key/value settings store the frontend mirrors its
 * preferences into.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ApplyNetworkSettings rebuilds the HTTP client from the persisted proxy /
 * timeout settings so the change takes effect without an app restart.
 */
export function ApplyNetworkSettings(): $CancellablePromise<void> {
    return $Call.ByID(890518201);
}

/**
 * ExportReading writes the reader's typography and layout preferences to a
 * file the reader chooses.
 * 
 * It goes through Go rather than through the webview because the WKWebView has
 * no download handler: an `<a download>` in this app saves nothing at all, and
 * says nothing about it either — the same reason the highlight export is
 * written here. An empty path means the reader cancelled, which is not an
 * error.
 */
export function ExportReading(content: string): $CancellablePromise<string> {
    return $Call.ByID(2661061024, content);
}

/**
 * GetSetting returns a setting's value, or null when the key is absent.
 */
export function GetSetting(key: string): $CancellablePromise<string | null> {
    return $Call.ByID(3324654838, key);
}

/**
 * ImportReading reads a settings file back. The frontend decides what to do
 * with what is in it — this only hands over the text, because what a reading
 * setting *is* is described there and nowhere here.
 */
export function ImportReading(): $CancellablePromise<string> {
    return $Call.ByID(786148353);
}

/**
 * SetSetting upserts a setting value. Changing the app icon also repaints
 * the running process so the Dock follows without a restart.
 */
export function SetSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2989640098, key, value);
}
