// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StorageService exposes the storage / data-management commands in the settings
 * "Advanced" panel.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/models/models.js";

/**
 * ClearLibrary deletes every book — and with it every chapter, highlight,
 * bookmark and reading position. Settings, shelves and tags survive.
 */
export function ClearLibrary(): $CancellablePromise<void> {
    return $Call.ByID(2819928319);
}

/**
 * ResetSettings clears every stored setting.
 */
export function ResetSettings(): $CancellablePromise<void> {
    return $Call.ByID(1866929919);
}

/**
 * StorageStats returns database size and library counts.
 */
export function StorageStats(): $CancellablePromise<models$0.StorageStats> {
    return $Call.ByID(1818933243);
}

/**
 * VacuumDB reclaims the pages deleted books left behind. It earns its own
 * button here because removing one illustrated book can free tens of megabytes
 * that SQLite will not hand back to the filesystem on its own.
 */
export function VacuumDB(): $CancellablePromise<void> {
    return $Call.ByID(3016139794);
}
