// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService exposes app-level commands not tied to a single domain: the
 * native tray, the window chrome, and fullscreen.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppInfo returns the running build's identity.
 */
export function AppInfo(): $CancellablePromise<$models.AppInfo | null> {
    return $Call.ByID(1463719132);
}

/**
 * CheckForUpdate asks the repository's release feed for the newest published
 * version. A repository with no releases yet reports up-to-date rather than
 * erroring — that is the normal state until the first packaged release.
 */
export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(4272845007);
}

/**
 * IsFullscreen reports the current window's fullscreen state so the UI
 * can seed itself on mount (or after a native-side toggle).
 */
export function IsFullscreen(): $CancellablePromise<boolean> {
    return $Call.ByID(3324046380);
}

/**
 * RefreshTray rebuilds the menu-bar tray, re-reading the UI language so its
 * labels match the current locale. No-op until the tray is wired in main.go.
 */
export function RefreshTray(): $CancellablePromise<void> {
    return $Call.ByID(1278130536);
}

/**
 * SetWindowBackground paints the native window backing the given colour. The
 * frontend mirrors the current theme's paper colour here on every appearance
 * change, so the strip a fast macOS resize exposes beyond the webview's last
 * frame matches the theme instead of flashing the (formerly hardcoded) light
 * paper in dark mode.
 */
export function SetWindowBackground(r: number, g: number, b: number): $CancellablePromise<void> {
    return $Call.ByID(3516783323, r, g, b);
}

/**
 * ToggleFullscreen flips the current window between fullscreen and normal
 * state. Real system-level fullscreen: on macOS the traffic-light bar and
 * menu bar hide via native NSWindow; on Windows/Linux the frame collapses
 * via Wails' fullscreen implementation. Returns the resulting state so the
 * UI can sync (a mac user pressing the green traffic-light directly still
 * fires this same state, so we treat the API as authoritative).
 */
export function ToggleFullscreen(): $CancellablePromise<boolean> {
    return $Call.ByID(3422122172);
}
