// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TagService exposes tag CRUD, ordering, and book tagging.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/models/models.js";

/**
 * CreateTag creates a tag (idempotent on name) and returns its id. An
 * empty/whitespace-only name is rejected at this chokepoint.
 */
export function CreateTag(name: string): $CancellablePromise<number> {
    return $Call.ByID(4213320178, name);
}

/**
 * DeleteTag removes a tag; its book links cascade.
 */
export function DeleteTag(id: number): $CancellablePromise<void> {
    return $Call.ByID(43089631, id);
}

/**
 * ListTags returns every tag with a live book count, ordered for the sidebar.
 */
export function ListTags(): $CancellablePromise<models$0.Tag[] | null> {
    return $Call.ByID(2758172995);
}

/**
 * RenameTag renames a tag, rejecting a clash with a different tag.
 */
export function RenameTag(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3540245144, id, name);
}

/**
 * ReorderTags persists a new tag ordering — ids in the desired display order.
 */
export function ReorderTags(ids: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(1425029536, ids);
}

/**
 * SetBookTag attaches (on = true) or detaches a tag from one book.
 */
export function SetBookTag(bookID: number, tagID: number, on: boolean): $CancellablePromise<void> {
    return $Call.ByID(2844794505, bookID, tagID, on);
}

/**
 * SetTagColor changes a tag's colour (a palette key).
 */
export function SetTagColor(id: number, color: string): $CancellablePromise<void> {
    return $Call.ByID(199989609, id, color);
}
