// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "books-imported": any;
            "library-changed": any;
            "tray-add-books": any;
            "tray-open-settings": any;
        }
    }
}
