// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InstalledFont is one downloaded font tracked in the installed_fonts table.
 * Files live in <dataDir>/fonts and are served to the webview at
 * /userfonts/<file>; the frontend registers an @font-face per row on startup.
 */
export interface InstalledFont {
    "id": string;
    "family": string;
    "label": string;
    "category": string;
    "cjk": boolean;
    "axis": string;
    "license": string;
    "source": string;
    "file": string;
    "ext": string;
    "bytes": number;
}

/**
 * LibraryCounts are the numbers beside the sidebar's smart shelves.
 */
export interface LibraryCounts {
    "all": number;
    "reading": number;
    "finished": number;
    "favorite": number;
    "highlights": number;
}
