// Package services holds the Wails-bound service structs — hiread's typed IPC
// boundary. Every exported method on a registered service becomes a
// frontend-callable command (with TS bindings generated by
// `wails3 generate bindings`). Services delegate all SQL to internal/db and
// never embed raw queries.
package services

import (
	"context"

	"hiread/internal/appstate"
)

// Services bundles every bound service so main.go can register them in one place.
type Services struct {
	Library    *LibraryService
	Collection *CollectionService
	Tag        *TagService
	Setting    *SettingService
	Highlight  *HighlightService
	Storage    *StorageService
	System     *SystemService
	AI         *AIService
	Font       *FontService
}

// New constructs every service over the shared application state.
func New(app *appstate.State) *Services {
	return &Services{
		Library:    &LibraryService{app: app},
		Collection: &CollectionService{app: app},
		Tag:        &TagService{app: app},
		Setting:    &SettingService{app: app},
		Highlight:  &HighlightService{app: app},
		Storage:    &StorageService{app: app},
		System:     &SystemService{app: app},
		AI:         &AIService{app: app},
		Font:       &FontService{app: app},
	}
}

// bg is the background context used by non-cancellable command handlers.
func bg() context.Context { return context.Background() }

// truncateRunes returns at most max runes of s without splitting a UTF-8
// boundary.
func truncateRunes(s string, max int) string {
	r := []rune(s)
	if len(r) <= max {
		return s
	}
	return string(r[:max])
}
