// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Book is a row in the library grid. It carries no chapter text — just what the
 * cover card shows and what sorting and filtering need.
 */
export interface Book {
    "id": number;
    "title": string;
    "author": string | null;
    "language": string | null;
    "publisher": string | null;
    "format": string;
    "fileName": string;
    "fileSize": number;
    "collectionId": number | null;

    /**
     * HasCover says whether to request cover bytes; the bytes themselves are
     * fetched separately so the list payload stays small.
     */
    "hasCover": boolean;
    "chapterCount": number;
    "charCount": number;
    "pageCount": number;
    "addedAt": string;
    "lastReadAt": string | null;
    "isFinished": boolean;
    "isFavorite": boolean;

    /**
     * Percent is how far through the book the reader is, 0..1.
     */
    "percent": number;

    /**
     * Tags currently attached to this book.
     */
    "tags": Tag[] | null;
}

/**
 * BookDetail is what the reader loads when a book is opened: everything in Book
 * plus the description, the table of contents and the saved position.
 */
export interface BookDetail {
    "id": number;
    "title": string;
    "author": string | null;
    "language": string | null;
    "publisher": string | null;
    "format": string;
    "fileName": string;
    "fileSize": number;
    "collectionId": number | null;

    /**
     * HasCover says whether to request cover bytes; the bytes themselves are
     * fetched separately so the list payload stays small.
     */
    "hasCover": boolean;
    "chapterCount": number;
    "charCount": number;
    "pageCount": number;
    "addedAt": string;
    "lastReadAt": string | null;
    "isFinished": boolean;
    "isFavorite": boolean;

    /**
     * Percent is how far through the book the reader is, 0..1.
     */
    "percent": number;

    /**
     * Tags currently attached to this book.
     */
    "tags": Tag[] | null;
    "description": string | null;
    "identifier": string | null;
    "publishedAt": string | null;
    "chapters": Chapter[] | null;
    "progress": Progress;
}

/**
 * Bookmark is a position the reader saved by hand.
 */
export interface Bookmark {
    "id": number;
    "bookId": number;
    "chapterIndex": number;
    "chapterRatio": number;
    "page": number | null;
    "label": string;
    "createdAt": string;
}

/**
 * Chapter is a table-of-contents entry: the chapter without its body.
 */
export interface Chapter {
    "index": number;
    "title": string;
    "level": number;

    /**
     * Href is the chapter's path inside the original container (EPUB), which is
     * what an intra-book link points at. nil for formats that have none.
     */
    "href": string | null;

    /**
     * CharCount drives both the reading-time estimate and the weight this
     * chapter carries in whole-book progress.
     */
    "charCount": number;
}

/**
 * ChapterContent is one chapter's readable body.
 */
export interface ChapterContent {
    "bookId": number;
    "index": number;
    "title": string;

    /**
     * HTML is sanitized and ready to render. Image references carry a data-res
     * attribute naming a book resource rather than a src the webview could
     * fetch on its own.
     */
    "html": string;
    "charCount": number;

    /**
     * AiSummary is the cached AI summary of this chapter, if one was generated.
     */
    "aiSummary": string | null;
}

/**
 * ChapterTranslation is one cached rendering of a chapter, keyed by target
 * language and engine.
 */
export interface ChapterTranslation {
    "lang": string;
    "engine": string;
    "title": string | null;
    "html": string;
}

/**
 * Collection is a shelf in the sidebar: a user-made grouping of books.
 */
export interface Collection {
    "id": number;
    "name": string;
    "position": number;

    /**
     * BookCount is computed at query time.
     */
    "bookCount": number;
}

/**
 * Highlight is a user highlight / annotation pinned to a span of a chapter's
 * rendered plain text. TextOffset plus Prefix / Suffix form a resilient anchor:
 * the offset is tried first, the context window second.
 */
export interface Highlight {
    "id": number;
    "bookId": number;
    "chapterIndex": number;

    /**
     * Quote is the highlighted text itself.
     */
    "quote": string;

    /**
     * Prefix is a short window of text immediately before the quote.
     */
    "prefix": string;

    /**
     * Suffix is a short window of text immediately after the quote.
     */
    "suffix": string;

    /**
     * TextOffset is the character offset of the quote within the chapter's
     * plain-text render.
     */
    "textOffset": number;

    /**
     * Color is a palette key resolved to a colour by the frontend.
     */
    "color": string;

    /**
     * Note is an optional user note; an empty string means no note.
     */
    "note": string;
    "createdAt": string;
}

/**
 * HighlightWithContext is Highlight enriched with the book and chapter it
 * belongs to, used by the highlights browser and the Markdown export. Reader
 * code keeps using the lean Highlight type.
 */
export interface HighlightWithContext {
    "id": number;
    "bookId": number;
    "chapterIndex": number;

    /**
     * Quote is the highlighted text itself.
     */
    "quote": string;

    /**
     * Prefix is a short window of text immediately before the quote.
     */
    "prefix": string;

    /**
     * Suffix is a short window of text immediately after the quote.
     */
    "suffix": string;

    /**
     * TextOffset is the character offset of the quote within the chapter's
     * plain-text render.
     */
    "textOffset": number;

    /**
     * Color is a palette key resolved to a colour by the frontend.
     */
    "color": string;

    /**
     * Note is an optional user note; an empty string means no note.
     */
    "note": string;
    "createdAt": string;
    "bookTitle": string;
    "bookAuthor": string | null;
    "chapterTitle": string;
}

/**
 * ImportResult reports what happened to one file in an import batch. The
 * frontend shows a per-file outcome rather than failing the whole batch on one
 * bad file.
 */
export interface ImportResult {
    "fileName": string;
    "bookId": number;
    "title": string;

    /**
     * Duplicate is set when the file is already in the library; BookID then
     * points at the copy that is already there.
     */
    "duplicate": boolean;

    /**
     * Error is a frontend i18n key when the file could not be imported.
     */
    "error": string;
}

/**
 * LibraryQuery filters the library grid, mirroring the sidebar selection. Kind
 * is one of all | reading | finished | favorite | collection | tag | format,
 * and Value carries the collection or tag id for the two that need one.
 */
export interface LibraryQuery {
    "kind": string;
    "value": number | null;
    "text": string | null;
}

/**
 * Progress is where the reader left off in a book.
 */
export interface Progress {
    "chapterIndex": number;

    /**
     * ChapterRatio is the scroll position within the chapter, 0..1.
     */
    "chapterRatio": number;

    /**
     * Page is the PDF page number, 1-based, and is meaningless for other formats.
     */
    "page": number;

    /**
     * Percent is progress through the whole book, 0..1.
     */
    "percent": number;
    "updatedAt": string;
}

/**
 * SearchHit is one full-text match inside a book.
 */
export interface SearchHit {
    "bookId": number;
    "bookTitle": string;
    "chapterIndex": number;
    "chapterTitle": string;

    /**
     * Snippet is the matching passage with the query terms wrapped in <mark>.
     */
    "snippet": string;
}

/**
 * StorageStats summarizes on-disk usage for the storage panel.
 */
export interface StorageStats {
    "dbBytes": number;
    "bookCount": number;
    "chapterCount": number;

    /**
     * ResourceBytes is how much of the database the books' images and PDF
     * originals account for.
     */
    "resourceBytes": number;
}

/**
 * Tag is a user-defined label that can be attached to any number of books.
 */
export interface Tag {
    "id": number;
    "name": string;

    /**
     * Color is a palette key (resolved to a colour by the frontend).
     */
    "color": string;
    "position": number;

    /**
     * BookCount is how many books currently carry this tag.
     */
    "bookCount": number;
}
