// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Message is one turn in a chat conversation. Role is "user" or "assistant".
 * Ask threads prior turns through so a follow-up question keeps its context;
 * single-turn callers (Summarize, Digest) pass exactly one user Message.
 */
export interface Message {
    "role": string;
    "content": string;
}
